### ISSUE TITLE
Improve Unit Test

### ISSUE THREAD

**Issue by zf2timo** [zf2timo/PHPUnitPrettyResultPrinter#4]
PHPUnit is used the wrong way. 
The Printer should be tested by PHPUnit and not used by it.

**Comment by zf2timo** [comment]
- [x] Travis Integration (per #22 )
- [x] PHP Coding Style Sniffer (per #24 
- [x] Unit Test with PHPT (per #23 )
- [x] Optimize Travis integration (per #25 )
